### PR TITLE
18:Add resource attributes to spans

### PR DESCRIPTION
**Pull request by vikrambe**

### CODE REVIEW

**Comment by tedsuo** [comment]
Hi @vikrambe. I believe we would also need to translate these resources a second time, from OTel trace.SpanData resources into Lightstep Tags here:
https://github.com/lightstep/opentelemetry-exporter-go/blob/master/lightstep/lightstep.go#L147

Longer term, this entire code path needs to change to avoid these extra allocations.

@rnburn @jmacd can you confirm this is correct?

**Comment by vikrambe** [comment]
@tedsuo Sure, i got it working yesterday. I will add some tests shortly

**Comment by andrewhsu** [comment]
@vikrambe hi, any update on the tests to add?

**Comment by vikrambe** [comment]
@andrewhsu sorry, i was busy with some critical work. I will add it today or earliest by tomorrow

**Comment by jmacd** [comment]
@vikrambe I will merge this and add tests myself in a subsequent PR.

**Comment by jmacd** [comment]
@vikrambe Thank you for your contribution!

**Pull request merged**
