### PR TITLE
fix zipkin trace id

### PR DESCRIPTION
**Pull request by chrisleavoy**
There are tracing systems which are not capable of propagating the entire 16 bytes of a trace-id. For better interoperability between a fully compliant systems with these existing systems, the following practices are recommended:

- When a system creates an outbound message and needs to generate a fully compliant 16 bytes trace-id from a shorter identifier, it SHOULD left pad the original identifier with zeroes. For example, the identifier 53ce929d0e0e4736, SHOULD be converted to trace-id value 000000000000000053ce929d0e0e4736.

- When a system receives an inbound message and needs to convert the 16 bytes trace-id to a shorter identifier, the rightmost part of trace-id SHOULD be used as this identifier. For instance, if the value of trace-id was 234a5bcd543ef3fa53ce929d0e0e4736 on an incoming request, tracing system SHOULD use identifier with the value of 53ce929d0e0e4736.

### CODE REVIEW

**Comment by kayousterhout** [comment]
@chrisleavoy would you mind updating the merge conflict here?

**Comment by chrisleavoy** [comment]
@kayousterhout done. I originally submitted the pr with a conflict on purpose as we wanted 60b6148 to be tagged as hot fix release v0.4.3.

**Comment by kayousterhout** [comment]
Ah ok I made a new release for you with your earlier commit (and an additional fix to fix the unit tests): https://github.com/lightstep/opentelemetry-exporter-go/releases/tag/v0.4.3 - let me know if you see any issues there.

I can also merge this PR if you merge in an update to fix the unit tests first: https://github.com/chrisleavoy/opentelemetry-exporter-go/pull/1

Thanks for fixing this!

**Comment by chrisleavoy** [comment]
Awesome thanks so much!

**Comment by chrisleavoy** [comment]
@kayousterhout , merged test update, tests pass now.

**Comment by kayousterhout** [comment]
Great thanks @chrisleavoy !

**Pull request merged**
